# Generated by Django 4.2.1 on 2023-06-02 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('data_criado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='cat_img')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='produto_img')),
                ('slug', models.SlugField(unique=True)),
                ('preco_mercado', models.PositiveIntegerField()),
                ('venda', models.PositiveIntegerField()),
                ('especificao', models.TextField()),
                ('detalhe', models.TextField()),
                ('garantia', models.CharField(blank=True, max_length=300, null=True)),
                ('return_devolucao', models.CharField(blank=True, max_length=300, null=True)),
                ('visualizacao', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Produto_Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenador_por', models.CharField(max_length=200)),
                ('endereco_envio', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('subtotal', models.PositiveIntegerField()),
                ('desconto', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('pedido_status', models.CharField(choices=[('Pedido Processando', 'Pedido Processando'), ('Pedido Recebido', 'Pedido Recebido'), ('Pedido Completado', 'Pedido Completado'), ('Pedido Cancelando', 'Pedido Cancelando'), ('Pedido a Caminho', 'Pedido a Caminho')], max_length=300)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=300, null=True)),
                ('endereco', models.CharField(max_length=300, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cliente'),
        ),
    ]
