# Generated by Django 4.1.7 on 2023-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_produto_image_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_status',
            field=models.CharField(choices=[('Pedido Cancelando', 'Pedido Cancelando'), ('Pedido Recebido', 'Pedido Recebido'), ('Pedido Processando', 'Pedido Processando'), ('Pedido Completado', 'Pedido Completado'), ('Pedido a Caminho', 'Pedido a Caminho')], max_length=300),
        ),
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(upload_to='media/produto_img'),
        ),
    ]
