# Generated by Django 4.2.1 on 2023-05-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cor_marcas_tamanhos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='produto_img')),
                ('nome', models.CharField(max_length=200)),
                ('detalhe', models.TextField()),
                ('especificao', models.TextField()),
                ('valor', models.PositiveBigIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.marcas')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tamanhos')),
            ],
        ),
    ]
