# Generated by Django 4.1.7 on 2023-05-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produto')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tamanhos')),
            ],
        ),
    ]
